export const ACCOUNT_LOAD_ADDRESS = 'ACCOUNT_LOAD_ADDRESS';
export const ACCOUNT_LOAD_ADDRESS_SUCCESS = 'ACCOUNT_LOAD_ADDRESS_SUCCESS';

export const ORDER_CREATION = 'ORDER_CREATION';
export const ORDER_CREATION_SUCCESS = 'ORDER_CREATION_SUCCESS';